# Generated by Django 5.1.6 on 2025-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='sleep',
            field=models.IntegerField(default=0),
        ),
    ]
