# Generated by Django 5.1.6 on 2025-04-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_foodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodlog',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
